export const GET_USERS_REQUESTED = 'GET_USERS_REQUESTED';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const GET_USERBYID_REQUESTED = 'GET_USERBYID_REQUESTED';
export const GET_USERBYID_SUCCESS = 'GET_USERBYID_SUCCESS';
export const GET_USERBYID_FAILED = 'GET_USERBYID_FAILED';

export const ADD_USERS_REQUESTED = 'ADD_USERS_REQUESTED';
export const ADD_USERS_SUCCESS = ' ADD_USERS_SUCCESS';
export const ADD_USERS_FAILED = 'ADD_USERS_FAILED';

export const SORT_USERS_REQUESTED = 'SORT_USERS_REQUESTED';
export const SORT_USERS_SUCCESS = 'SORT_USERS_SUCCESS';
export const SORT_USERS_FAILED = 'SORT_USERS_FAILED';


export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS';



